# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d333b843a7b62b9e32e154645627b161cebb10dd6a9f97c7f434bf6e2d81877a51d3de668c039d1a4cdde0c8181003f36f94b7a982d07244ea64471ab0621724

test:
  secret_key_base: a84f89da2de4396bcb24fd118f238ba3f4f3a74b5aa4b6a5f801cbcdbdff15931dbbfe68616fa932f8a5256a58f4cf6d5983f40fa134a4eea4edc60a38b56201

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
